### ISSUE TITLE
Overflow Error

### ISSUE THREAD

**Issue by AyushRaghuvanshi** [Pudv95/Google-Clone#2]
![image](https://github.com/Pudv95/Google-Clone/assets/62144720/4bdb2ab0-205b-41c7-b392-5eaede5d08a9)

You added Responsive height to the list but the Text field is still constant.
This will break on any devices smaller than yours.

Could've used Expanded Widget here.
https://www.youtube.com/watch?v=_rnZaagadyo&embeds_referring_euri=https%3A%2F%2Fapi.flutter.dev%2F

**Comment by Pudv95** [comment]
Overflow Resolved by using Expanded Widget
