### ISSUE TITLE
Wrong Implementation of unfocus

### ISSUE THREAD

**Issue by AyushRaghuvanshi** [Pudv95/Google-Clone#7]
![image](https://github.com/Pudv95/Google-Clone/assets/62144720/18b82010-b5d5-41b3-843d-d449919d15bd)
Rather than this do this.
![image](https://github.com/Pudv95/Google-Clone/assets/62144720/0749e2c5-491e-4da1-9100-f60ffa66064b)
I will Explain the reason in meet.

**Comment by Pudv95** [comment]
Implemented Listener in place of GestureDetector
